global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # ★ 핵심: Docker 내부에서 내 PC(로컬호스트)를 찾으려면
      # 'localhost' 대신 컨테이너 이름('backend')을 써야한다!
      - targets: ['backend:8080']